---
title: "Homework 1"
author: "Hanim Zul, Shafiqah Azman, Iffah, Lisa"
date: "September 8, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

hello

## R Markdown

##Question 4

##ii)
```{r}
x=rnorm(100, 0, 1)
```

```{r}
A=median(x)
B=mean(x)
C=var(x)
```

#Empirical median of x is `r A`
#Empirical mean of x is `r B`
#Empirical variance of x is `r C`

```{r}
hist(x,  main = paste("Histogram of 100 random samples from a standard normal distribution" ))
```

#The histogram of x is approximately symmetrical with bell-shaped. This histogram has similar shape as the histogram of a standard normal distribution with mean=0 and standard deviation=1.

$$
\begin{aligned}
\mathbb{E} [\mathrm{var}\{ v_1(\hat \theta, n) \}] &=  \mathrm{var}\{ v_1( \theta_0, n)\} 
+ \mathbb{E} [\ O _p \{ \boldsymbol D_1 (\theta^*, n)(\hat \theta- \theta_0), ...,
\boldsymbol D_p (\theta^*, n)(\hat \theta- \theta_0) \}] \\
&=\mathrm{var}\{ v_1( \theta_0, n)\} + O(n^{-2})
\end{aligned}

$$

$\boldsymbol A \equiv [a_{i,j}]_{i,j=1,...,p^.}$